global using Autofac;
global using Autofac.Extensions.DependencyInjection;
global using Framework.Library.Web;
global using MediatR;
global using Memorabilia.Application.Configuration;
global using Memorabilia.Application.Features.Admin.AccomplishmentTypes;
global using Memorabilia.Application.Features.Admin.AcquisitionTypes;
global using Memorabilia.Application.Features.User;
global using Memorabilia.MinimalAPI.Extensions;
global using Memorabilia.MinimalAPI.Interfaces;
global using Memorabilia.MinimalAPI.Models;
global using Memorabilia.MinimalAPI.Models.Admin.AccomplishmentTypes;
global using Memorabilia.MinimalAPI.Models.Admin.AcquisitionTypes;
global using Memorabilia.Repository;
global using Memorabilia.Repository.Configuration;
global using Microsoft.EntityFrameworkCore;
global using Constant = Memorabilia.Domain.Constants;
global using Enum = Memorabilia.Domain.Enums;
global using Entity = Memorabilia.Domain.Entities;
global using Handler = Memorabilia.MinimalAPI.Handlers;
