global using FluentValidation;
global using FluentValidation.Results;
global using Memorabilia.Domain.Enums;
global using Memorabilia.Domain.Extensions;
global using Memorabilia.Domain.Paging;
global using Memorabilia.Domain.SearchModels.Autographs;
global using Microsoft.EntityFrameworkCore;
global using System;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Diagnostics.CodeAnalysis;
global using System.IO;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Reflection;
global using System.Text;
global using System.Threading.Tasks;
global using Constant = Memorabilia.Domain.Constants;
global using Entity = Memorabilia.Domain.Entities;
